(pp-include ("bits/wordsize.h"))
(typedef (char :signed) int8_t)
(typedef short int16_t)
(typedef int int32_t)
(pp-if (== __WORDSIZE 64))
(typedef long int64_t)
(pp-else)
(typedef (long long) int64_t)
(pp-endif)
(typedef (char :unsigned) uint8_t)
(typedef (short :unsigned) uint16_t)
(typedef (int :unsigned) uint32_t)
(pp-if (== __WORDSIZE 64))
(typedef (long long :unsigned) uint64_t)
(pp-endif)
