(int ($function f (void))
     (* ($function fip ()))
     ($function (* pfi) ()))
(int ($function (* ($array apfi 3))
                ((int (* x))
                 (int (* y)))))
(void ($function addscalar ((int n)
                            (int m)
                            (double ($array ($array a n) (+ (* n m) 300)))
                            (double x))))
(int ($function main ((int argc)
                      (char ((* *) argv))))
     ($block
      (int (x 5))
      (int (y 6))
      ($call (* (@ apfi 0)) (& x) (& y))
      (double ($array ($array b 4) 308))
      ($call addscalar 4 2 b 2.17)
      (return 0)))
(void ($function addscalar ((int n)
                            (int m)
                            (double ($array ($array a n) (+ (* n m) 300)))
                            (double x)))
      ($block
       (for (int (i 0)) (< i n) (i ++)
            ($block
             (for (int (j 0) (k (+ (* n m) 300))) (< j k) (j ++)
                  ($block
                   (+= (@ (@ a i) j) x)))))))
(int ($function
      (* ($function fpfi ((int ($function * (long))) int)))
      (int $...)))
(double ($function maximum ((int n)
                            (int m)
                            (double ($array ($array a n) m)))))
(double ($function maximum ((int n)
                            (int m)
                            (double ($array ($array a *) *)))))
(double ($function maximum ((int n)
                            (int m)
                            (double ($array ($array a) *)))))
(double ($function maximum ((int n)
                            (int m)
                            (double ($array ($array a) m)))))
(void ($function f ((double ($array ((* restrict) a) 5)))))
(void ($function f ((double ($array ($array a restrict) 5)))))
(void ($function f ((double ($array ($array a restrict 3) 5)))))
(void ($function f ((double ($array ($array a restrict static 3) 5)))))
