(char (c_c ($char "c")))
(char (c_sq ($char "'")))
(char (c_dq ($char "\"")))
(char (c_qm ($char "?")))
(char (c_bs ($char "\\")))
(char (c_0 ($char "\0")))
(char (c_hex_c2 ($char "\xc2")))
(char (c_alert ($char "\a")))
(char (c_backspace ($char "\b")))
(char (c_formfeed ($char "\f")))
(char (c_nl ($char "\n")))
(char (c_cr ($char "\r")))
(char (c_tab ($char "\t")))
(char (c_vtab ($char "\v")))
(char (c_space ($char " ")))
