(int (i 3.5))
((double complex) (c (+ 5 (* 3 I))))
(int (($array x) (1 3 5)))
(int (($array ($array y 4) 3)
      ((1 3 5)
       (2 4 6)
       (3 5 7))))
(int (($array ($array y 4) 3)
      (1 3 5 2 4 6 3 5 7)))
(int (($array ($array z 4) 3)
      ((1) (2) (3) (4))))
((struct ((int ($array a 3) b)))
 (($array w) ((1) 2)))
((typedef int) ($array A))
(A (a (1 2)) (b (3 4 5)))
(int (($array a) (1 2)) (($array b) (3 4 5)))
(char (($array s) "abc") (($array t 3) "abc"))
(char (($array s) (($char "a") ($char "b") ($char "c") ($char "\0")))
      (($array t) (($char "a") ($char "b") ($char "c"))))
((enum (member_one member_two)))
((const char) ((* ($array nm)) (((@ member_two) "member_two")
                               ((@ member_one) "member_one"))))
(div_t (answer ((($at quot) 2) (($at rem) -1))))
((struct ((int ($array a 3) b)))
 (($array w) ((((@ 0) ($at a)) (1))
              (((@ 1) ($at a) (@ 0)) 2))))
(int (($array a MAX) (1 3 5 7 9 ((@ (- MAX 5)) 8) 6 4 2 0)))
