(int a)
(int ($array n 10))
(int ($array n))
(int ($function substring (((const char) (* s))
                           (int start)
                           (int end))))
(int ($array ($array x 3) 5))
