(int (i1 1234))
(int (i2 -1234))
(float (f1 125.25))
(float (f2 -125.25))
(double (d1 125.25))
(double (d2 -125.25))
(char (c_c (char-const "c")))
(char (c_sq (char-const "'")))
(char (c_dq (char-const "\"")))
(char (c_qm (char-const "?")))
(char (c_bs (char-const "\\")))
(char (c_0 (char-const "\0")))
(char (c_hex_c2 (char-const "\xc2")))
(char (c_alert (char-const "\a")))
(char (c_backspace (char-const "\b")))
(char (c_formfeed (char-const "\f")))
(char (c_nl (char-const "\n")))
(char (c_cr (char-const "\r")))
(char (c_tab (char-const "\t")))
(char (c_vtab (char-const "\v")))
(char (c_space (char-const " ")))
((enum (TRUE FALSE)) (bool FALSE))
